// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package tictactoe

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Game               protoreflect.MessageDescriptor
	fd_Game_gameId        protoreflect.FieldDescriptor
	fd_Game_adminAddress  protoreflect.FieldDescriptor
	fd_Game_Status        protoreflect.FieldDescriptor
	fd_Game_board         protoreflect.FieldDescriptor
	fd_Game_NextMove      protoreflect.FieldDescriptor
	fd_Game_Winner        protoreflect.FieldDescriptor
	fd_Game_first_player  protoreflect.FieldDescriptor
	fd_Game_second_player protoreflect.FieldDescriptor
)

func init() {
	file_ticchain_tictactoe_game_proto_init()
	md_Game = File_ticchain_tictactoe_game_proto.Messages().ByName("Game")
	fd_Game_gameId = md_Game.Fields().ByName("gameId")
	fd_Game_adminAddress = md_Game.Fields().ByName("adminAddress")
	fd_Game_Status = md_Game.Fields().ByName("Status")
	fd_Game_board = md_Game.Fields().ByName("board")
	fd_Game_NextMove = md_Game.Fields().ByName("NextMove")
	fd_Game_Winner = md_Game.Fields().ByName("Winner")
	fd_Game_first_player = md_Game.Fields().ByName("first_player")
	fd_Game_second_player = md_Game.Fields().ByName("second_player")
}

var _ protoreflect.Message = (*fastReflection_Game)(nil)

type fastReflection_Game Game

func (x *Game) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Game)(x)
}

func (x *Game) slowProtoReflect() protoreflect.Message {
	mi := &file_ticchain_tictactoe_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Game_messageType fastReflection_Game_messageType
var _ protoreflect.MessageType = fastReflection_Game_messageType{}

type fastReflection_Game_messageType struct{}

func (x fastReflection_Game_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Game)(nil)
}
func (x fastReflection_Game_messageType) New() protoreflect.Message {
	return new(fastReflection_Game)
}
func (x fastReflection_Game_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Game
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Game) Descriptor() protoreflect.MessageDescriptor {
	return md_Game
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Game) Type() protoreflect.MessageType {
	return _fastReflection_Game_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Game) New() protoreflect.Message {
	return new(fastReflection_Game)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Game) Interface() protoreflect.ProtoMessage {
	return (*Game)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Game) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.GameId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.GameId)
		if !f(fd_Game_gameId, value) {
			return
		}
	}
	if x.AdminAddress != "" {
		value := protoreflect.ValueOfString(x.AdminAddress)
		if !f(fd_Game_adminAddress, value) {
			return
		}
	}
	if x.Status != "" {
		value := protoreflect.ValueOfString(x.Status)
		if !f(fd_Game_Status, value) {
			return
		}
	}
	if x.Board != "" {
		value := protoreflect.ValueOfString(x.Board)
		if !f(fd_Game_board, value) {
			return
		}
	}
	if x.NextMove != "" {
		value := protoreflect.ValueOfString(x.NextMove)
		if !f(fd_Game_NextMove, value) {
			return
		}
	}
	if x.Winner != "" {
		value := protoreflect.ValueOfString(x.Winner)
		if !f(fd_Game_Winner, value) {
			return
		}
	}
	if x.FirstPlayer != nil {
		value := protoreflect.ValueOfMessage(x.FirstPlayer.ProtoReflect())
		if !f(fd_Game_first_player, value) {
			return
		}
	}
	if x.SecondPlayer != nil {
		value := protoreflect.ValueOfMessage(x.SecondPlayer.ProtoReflect())
		if !f(fd_Game_second_player, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Game) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ticchain.tictactoe.Game.gameId":
		return x.GameId != uint64(0)
	case "ticchain.tictactoe.Game.adminAddress":
		return x.AdminAddress != ""
	case "ticchain.tictactoe.Game.Status":
		return x.Status != ""
	case "ticchain.tictactoe.Game.board":
		return x.Board != ""
	case "ticchain.tictactoe.Game.NextMove":
		return x.NextMove != ""
	case "ticchain.tictactoe.Game.Winner":
		return x.Winner != ""
	case "ticchain.tictactoe.Game.first_player":
		return x.FirstPlayer != nil
	case "ticchain.tictactoe.Game.second_player":
		return x.SecondPlayer != nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Game"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Game does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Game) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ticchain.tictactoe.Game.gameId":
		x.GameId = uint64(0)
	case "ticchain.tictactoe.Game.adminAddress":
		x.AdminAddress = ""
	case "ticchain.tictactoe.Game.Status":
		x.Status = ""
	case "ticchain.tictactoe.Game.board":
		x.Board = ""
	case "ticchain.tictactoe.Game.NextMove":
		x.NextMove = ""
	case "ticchain.tictactoe.Game.Winner":
		x.Winner = ""
	case "ticchain.tictactoe.Game.first_player":
		x.FirstPlayer = nil
	case "ticchain.tictactoe.Game.second_player":
		x.SecondPlayer = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Game"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Game does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Game) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ticchain.tictactoe.Game.gameId":
		value := x.GameId
		return protoreflect.ValueOfUint64(value)
	case "ticchain.tictactoe.Game.adminAddress":
		value := x.AdminAddress
		return protoreflect.ValueOfString(value)
	case "ticchain.tictactoe.Game.Status":
		value := x.Status
		return protoreflect.ValueOfString(value)
	case "ticchain.tictactoe.Game.board":
		value := x.Board
		return protoreflect.ValueOfString(value)
	case "ticchain.tictactoe.Game.NextMove":
		value := x.NextMove
		return protoreflect.ValueOfString(value)
	case "ticchain.tictactoe.Game.Winner":
		value := x.Winner
		return protoreflect.ValueOfString(value)
	case "ticchain.tictactoe.Game.first_player":
		value := x.FirstPlayer
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "ticchain.tictactoe.Game.second_player":
		value := x.SecondPlayer
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Game"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Game does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Game) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ticchain.tictactoe.Game.gameId":
		x.GameId = value.Uint()
	case "ticchain.tictactoe.Game.adminAddress":
		x.AdminAddress = value.Interface().(string)
	case "ticchain.tictactoe.Game.Status":
		x.Status = value.Interface().(string)
	case "ticchain.tictactoe.Game.board":
		x.Board = value.Interface().(string)
	case "ticchain.tictactoe.Game.NextMove":
		x.NextMove = value.Interface().(string)
	case "ticchain.tictactoe.Game.Winner":
		x.Winner = value.Interface().(string)
	case "ticchain.tictactoe.Game.first_player":
		x.FirstPlayer = value.Message().Interface().(*Player)
	case "ticchain.tictactoe.Game.second_player":
		x.SecondPlayer = value.Message().Interface().(*Player)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Game"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Game does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Game) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ticchain.tictactoe.Game.first_player":
		if x.FirstPlayer == nil {
			x.FirstPlayer = new(Player)
		}
		return protoreflect.ValueOfMessage(x.FirstPlayer.ProtoReflect())
	case "ticchain.tictactoe.Game.second_player":
		if x.SecondPlayer == nil {
			x.SecondPlayer = new(Player)
		}
		return protoreflect.ValueOfMessage(x.SecondPlayer.ProtoReflect())
	case "ticchain.tictactoe.Game.gameId":
		panic(fmt.Errorf("field gameId of message ticchain.tictactoe.Game is not mutable"))
	case "ticchain.tictactoe.Game.adminAddress":
		panic(fmt.Errorf("field adminAddress of message ticchain.tictactoe.Game is not mutable"))
	case "ticchain.tictactoe.Game.Status":
		panic(fmt.Errorf("field Status of message ticchain.tictactoe.Game is not mutable"))
	case "ticchain.tictactoe.Game.board":
		panic(fmt.Errorf("field board of message ticchain.tictactoe.Game is not mutable"))
	case "ticchain.tictactoe.Game.NextMove":
		panic(fmt.Errorf("field NextMove of message ticchain.tictactoe.Game is not mutable"))
	case "ticchain.tictactoe.Game.Winner":
		panic(fmt.Errorf("field Winner of message ticchain.tictactoe.Game is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Game"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Game does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Game) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ticchain.tictactoe.Game.gameId":
		return protoreflect.ValueOfUint64(uint64(0))
	case "ticchain.tictactoe.Game.adminAddress":
		return protoreflect.ValueOfString("")
	case "ticchain.tictactoe.Game.Status":
		return protoreflect.ValueOfString("")
	case "ticchain.tictactoe.Game.board":
		return protoreflect.ValueOfString("")
	case "ticchain.tictactoe.Game.NextMove":
		return protoreflect.ValueOfString("")
	case "ticchain.tictactoe.Game.Winner":
		return protoreflect.ValueOfString("")
	case "ticchain.tictactoe.Game.first_player":
		m := new(Player)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "ticchain.tictactoe.Game.second_player":
		m := new(Player)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Game"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Game does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Game) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ticchain.tictactoe.Game", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Game) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Game) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Game) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Game) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Game)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.GameId != 0 {
			n += 1 + runtime.Sov(uint64(x.GameId))
		}
		l = len(x.AdminAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Status)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Board)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NextMove)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Winner)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.FirstPlayer != nil {
			l = options.Size(x.FirstPlayer)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.SecondPlayer != nil {
			l = options.Size(x.SecondPlayer)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Game)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.SecondPlayer != nil {
			encoded, err := options.Marshal(x.SecondPlayer)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x42
		}
		if x.FirstPlayer != nil {
			encoded, err := options.Marshal(x.FirstPlayer)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.Winner) > 0 {
			i -= len(x.Winner)
			copy(dAtA[i:], x.Winner)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Winner)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.NextMove) > 0 {
			i -= len(x.NextMove)
			copy(dAtA[i:], x.NextMove)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NextMove)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Board) > 0 {
			i -= len(x.Board)
			copy(dAtA[i:], x.Board)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Board)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Status) > 0 {
			i -= len(x.Status)
			copy(dAtA[i:], x.Status)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Status)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.AdminAddress) > 0 {
			i -= len(x.AdminAddress)
			copy(dAtA[i:], x.AdminAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AdminAddress)))
			i--
			dAtA[i] = 0x12
		}
		if x.GameId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.GameId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Game)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Game: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Game: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GameId", wireType)
				}
				x.GameId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.GameId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AdminAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AdminAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Status = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Board", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Board = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NextMove", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NextMove = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Winner", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Winner = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FirstPlayer", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.FirstPlayer == nil {
					x.FirstPlayer = &Player{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.FirstPlayer); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SecondPlayer", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.SecondPlayer == nil {
					x.SecondPlayer = &Player{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.SecondPlayer); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_Player           protoreflect.MessageDescriptor
	fd_Player_player_id protoreflect.FieldDescriptor
	fd_Player_symbol    protoreflect.FieldDescriptor
	fd_Player_points    protoreflect.FieldDescriptor
)

func init() {
	file_ticchain_tictactoe_game_proto_init()
	md_Player = File_ticchain_tictactoe_game_proto.Messages().ByName("Player")
	fd_Player_player_id = md_Player.Fields().ByName("player_id")
	fd_Player_symbol = md_Player.Fields().ByName("symbol")
	fd_Player_points = md_Player.Fields().ByName("points")
}

var _ protoreflect.Message = (*fastReflection_Player)(nil)

type fastReflection_Player Player

func (x *Player) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Player)(x)
}

func (x *Player) slowProtoReflect() protoreflect.Message {
	mi := &file_ticchain_tictactoe_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Player_messageType fastReflection_Player_messageType
var _ protoreflect.MessageType = fastReflection_Player_messageType{}

type fastReflection_Player_messageType struct{}

func (x fastReflection_Player_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Player)(nil)
}
func (x fastReflection_Player_messageType) New() protoreflect.Message {
	return new(fastReflection_Player)
}
func (x fastReflection_Player_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Player
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Player) Descriptor() protoreflect.MessageDescriptor {
	return md_Player
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Player) Type() protoreflect.MessageType {
	return _fastReflection_Player_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Player) New() protoreflect.Message {
	return new(fastReflection_Player)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Player) Interface() protoreflect.ProtoMessage {
	return (*Player)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Player) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.PlayerId != "" {
		value := protoreflect.ValueOfString(x.PlayerId)
		if !f(fd_Player_player_id, value) {
			return
		}
	}
	if x.Symbol != "" {
		value := protoreflect.ValueOfString(x.Symbol)
		if !f(fd_Player_symbol, value) {
			return
		}
	}
	if x.Points != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Points)
		if !f(fd_Player_points, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Player) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ticchain.tictactoe.Player.player_id":
		return x.PlayerId != ""
	case "ticchain.tictactoe.Player.symbol":
		return x.Symbol != ""
	case "ticchain.tictactoe.Player.points":
		return x.Points != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Player"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Player does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Player) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ticchain.tictactoe.Player.player_id":
		x.PlayerId = ""
	case "ticchain.tictactoe.Player.symbol":
		x.Symbol = ""
	case "ticchain.tictactoe.Player.points":
		x.Points = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Player"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Player does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Player) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ticchain.tictactoe.Player.player_id":
		value := x.PlayerId
		return protoreflect.ValueOfString(value)
	case "ticchain.tictactoe.Player.symbol":
		value := x.Symbol
		return protoreflect.ValueOfString(value)
	case "ticchain.tictactoe.Player.points":
		value := x.Points
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Player"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Player does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Player) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ticchain.tictactoe.Player.player_id":
		x.PlayerId = value.Interface().(string)
	case "ticchain.tictactoe.Player.symbol":
		x.Symbol = value.Interface().(string)
	case "ticchain.tictactoe.Player.points":
		x.Points = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Player"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Player does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Player) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ticchain.tictactoe.Player.player_id":
		panic(fmt.Errorf("field player_id of message ticchain.tictactoe.Player is not mutable"))
	case "ticchain.tictactoe.Player.symbol":
		panic(fmt.Errorf("field symbol of message ticchain.tictactoe.Player is not mutable"))
	case "ticchain.tictactoe.Player.points":
		panic(fmt.Errorf("field points of message ticchain.tictactoe.Player is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Player"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Player does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Player) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ticchain.tictactoe.Player.player_id":
		return protoreflect.ValueOfString("")
	case "ticchain.tictactoe.Player.symbol":
		return protoreflect.ValueOfString("")
	case "ticchain.tictactoe.Player.points":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ticchain.tictactoe.Player"))
		}
		panic(fmt.Errorf("message ticchain.tictactoe.Player does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Player) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ticchain.tictactoe.Player", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Player) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Player) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Player) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Player) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Player)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.PlayerId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Symbol)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Points != 0 {
			n += 1 + runtime.Sov(uint64(x.Points))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Player)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Points != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Points))
			i--
			dAtA[i] = 0x18
		}
		if len(x.Symbol) > 0 {
			i -= len(x.Symbol)
			copy(dAtA[i:], x.Symbol)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Symbol)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.PlayerId) > 0 {
			i -= len(x.PlayerId)
			copy(dAtA[i:], x.PlayerId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PlayerId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Player)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Player: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Player: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PlayerId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Symbol = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Points", wireType)
				}
				x.Points = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Points |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ticchain/tictactoe/game.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId       uint64 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AdminAddress string `protobuf:"bytes,2,opt,name=adminAddress,proto3" json:"adminAddress,omitempty"`
	Status       string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Board        string `protobuf:"bytes,4,opt,name=board,proto3" json:"board,omitempty"`
	NextMove     string `protobuf:"bytes,5,opt,name=NextMove,proto3" json:"NextMove,omitempty"`
	Winner       string `protobuf:"bytes,6,opt,name=Winner,proto3" json:"Winner,omitempty"`
	// First player
	FirstPlayer *Player `protobuf:"bytes,7,opt,name=first_player,json=firstPlayer,proto3" json:"first_player,omitempty"`
	// Opponent (Second player)
	SecondPlayer *Player `protobuf:"bytes,8,opt,name=second_player,json=secondPlayer,proto3" json:"second_player,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticchain_tictactoe_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_ticchain_tictactoe_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetGameId() uint64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Game) GetAdminAddress() string {
	if x != nil {
		return x.AdminAddress
	}
	return ""
}

func (x *Game) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Game) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *Game) GetNextMove() string {
	if x != nil {
		return x.NextMove
	}
	return ""
}

func (x *Game) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *Game) GetFirstPlayer() *Player {
	if x != nil {
		return x.FirstPlayer
	}
	return nil
}

func (x *Game) GetSecondPlayer() *Player {
	if x != nil {
		return x.SecondPlayer
	}
	return nil
}

// Message representing a player.
type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Symbol   string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // X or O
	Points   uint64 `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticchain_tictactoe_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_ticchain_tictactoe_game_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Player) GetPoints() uint64 {
	if x != nil {
		return x.Points
	}
	return 0
}

var File_ticchain_tictactoe_game_proto protoreflect.FileDescriptor

var file_ticchain_tictactoe_game_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x74, 0x69, 0x63, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x69, 0x63, 0x74, 0x61,
	0x63, 0x74, 0x6f, 0x65, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x74, 0x69, 0x63, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63,
	0x74, 0x6f, 0x65, 0x22, 0xa4, 0x02, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f,
	0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x65, 0x78, 0x74, 0x4d, 0x6f,
	0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0c, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x74, 0x69, 0x63, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x69, 0x63, 0x74,
	0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0b, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0d, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x74, 0x69, 0x63, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x69, 0x63, 0x74,
	0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0c, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x55, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x42, 0xb1, 0x01, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x63, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x42, 0x09, 0x47, 0x61,
	0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x23, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x69, 0x63, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0xa2, 0x02,
	0x03, 0x54, 0x54, 0x58, 0xaa, 0x02, 0x12, 0x54, 0x69, 0x63, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x54, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0xca, 0x02, 0x12, 0x54, 0x69, 0x63, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5c, 0x54, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0xe2, 0x02,
	0x1e, 0x54, 0x69, 0x63, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x54, 0x69, 0x63, 0x74, 0x61, 0x63,
	0x74, 0x6f, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x13, 0x54, 0x69, 0x63, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x54, 0x69, 0x63, 0x74,
	0x61, 0x63, 0x74, 0x6f, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticchain_tictactoe_game_proto_rawDescOnce sync.Once
	file_ticchain_tictactoe_game_proto_rawDescData = file_ticchain_tictactoe_game_proto_rawDesc
)

func file_ticchain_tictactoe_game_proto_rawDescGZIP() []byte {
	file_ticchain_tictactoe_game_proto_rawDescOnce.Do(func() {
		file_ticchain_tictactoe_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticchain_tictactoe_game_proto_rawDescData)
	})
	return file_ticchain_tictactoe_game_proto_rawDescData
}

var file_ticchain_tictactoe_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ticchain_tictactoe_game_proto_goTypes = []interface{}{
	(*Game)(nil),   // 0: ticchain.tictactoe.Game
	(*Player)(nil), // 1: ticchain.tictactoe.Player
}
var file_ticchain_tictactoe_game_proto_depIdxs = []int32{
	1, // 0: ticchain.tictactoe.Game.first_player:type_name -> ticchain.tictactoe.Player
	1, // 1: ticchain.tictactoe.Game.second_player:type_name -> ticchain.tictactoe.Player
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ticchain_tictactoe_game_proto_init() }
func file_ticchain_tictactoe_game_proto_init() {
	if File_ticchain_tictactoe_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ticchain_tictactoe_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticchain_tictactoe_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticchain_tictactoe_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticchain_tictactoe_game_proto_goTypes,
		DependencyIndexes: file_ticchain_tictactoe_game_proto_depIdxs,
		MessageInfos:      file_ticchain_tictactoe_game_proto_msgTypes,
	}.Build()
	File_ticchain_tictactoe_game_proto = out.File
	file_ticchain_tictactoe_game_proto_rawDesc = nil
	file_ticchain_tictactoe_game_proto_goTypes = nil
	file_ticchain_tictactoe_game_proto_depIdxs = nil
}
