// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ticchain/tictactoe/query.proto

package tictactoe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName         = "/ticchain.tictactoe.Query/Params"
	Query_Game_FullMethodName           = "/ticchain.tictactoe.Query/Game"
	Query_GameAll_FullMethodName        = "/ticchain.tictactoe.Query/GameAll"
	Query_GameBoard_FullMethodName      = "/ticchain.tictactoe.Query/GameBoard"
	Query_GameBoardAll_FullMethodName   = "/ticchain.tictactoe.Query/GameBoardAll"
	Query_LeaderboardAll_FullMethodName = "/ticchain.tictactoe.Query/LeaderboardAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Game items.
	Game(ctx context.Context, in *QueryGetGameRequest, opts ...grpc.CallOption) (*QueryGetGameResponse, error)
	GameAll(ctx context.Context, in *QueryAllGameRequest, opts ...grpc.CallOption) (*QueryAllGameResponse, error)
	GameBoard(ctx context.Context, in *QueryGetGameBoardRequest, opts ...grpc.CallOption) (*QueryGetGameBoardResponse, error)
	GameBoardAll(ctx context.Context, in *QueryAllGameBoardRequest, opts ...grpc.CallOption) (*QueryAllGameBoardResponse, error)
	// Queries a list of Leaderboard items.
	LeaderboardAll(ctx context.Context, in *QueryAllLeaderboardRequest, opts ...grpc.CallOption) (*QueryAllLeaderboardResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Game(ctx context.Context, in *QueryGetGameRequest, opts ...grpc.CallOption) (*QueryGetGameResponse, error) {
	out := new(QueryGetGameResponse)
	err := c.cc.Invoke(ctx, Query_Game_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GameAll(ctx context.Context, in *QueryAllGameRequest, opts ...grpc.CallOption) (*QueryAllGameResponse, error) {
	out := new(QueryAllGameResponse)
	err := c.cc.Invoke(ctx, Query_GameAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GameBoard(ctx context.Context, in *QueryGetGameBoardRequest, opts ...grpc.CallOption) (*QueryGetGameBoardResponse, error) {
	out := new(QueryGetGameBoardResponse)
	err := c.cc.Invoke(ctx, Query_GameBoard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GameBoardAll(ctx context.Context, in *QueryAllGameBoardRequest, opts ...grpc.CallOption) (*QueryAllGameBoardResponse, error) {
	out := new(QueryAllGameBoardResponse)
	err := c.cc.Invoke(ctx, Query_GameBoardAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LeaderboardAll(ctx context.Context, in *QueryAllLeaderboardRequest, opts ...grpc.CallOption) (*QueryAllLeaderboardResponse, error) {
	out := new(QueryAllLeaderboardResponse)
	err := c.cc.Invoke(ctx, Query_LeaderboardAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Game items.
	Game(context.Context, *QueryGetGameRequest) (*QueryGetGameResponse, error)
	GameAll(context.Context, *QueryAllGameRequest) (*QueryAllGameResponse, error)
	GameBoard(context.Context, *QueryGetGameBoardRequest) (*QueryGetGameBoardResponse, error)
	GameBoardAll(context.Context, *QueryAllGameBoardRequest) (*QueryAllGameBoardResponse, error)
	// Queries a list of Leaderboard items.
	LeaderboardAll(context.Context, *QueryAllLeaderboardRequest) (*QueryAllLeaderboardResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Game(context.Context, *QueryGetGameRequest) (*QueryGetGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Game not implemented")
}
func (UnimplementedQueryServer) GameAll(context.Context, *QueryAllGameRequest) (*QueryAllGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameAll not implemented")
}
func (UnimplementedQueryServer) GameBoard(context.Context, *QueryGetGameBoardRequest) (*QueryGetGameBoardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameBoard not implemented")
}
func (UnimplementedQueryServer) GameBoardAll(context.Context, *QueryAllGameBoardRequest) (*QueryAllGameBoardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameBoardAll not implemented")
}
func (UnimplementedQueryServer) LeaderboardAll(context.Context, *QueryAllLeaderboardRequest) (*QueryAllLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaderboardAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Game_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Game(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Game_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Game(ctx, req.(*QueryGetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GameAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GameAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GameAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GameAll(ctx, req.(*QueryAllGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GameBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGameBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GameBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GameBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GameBoard(ctx, req.(*QueryGetGameBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GameBoardAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllGameBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GameBoardAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GameBoardAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GameBoardAll(ctx, req.(*QueryAllGameBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LeaderboardAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LeaderboardAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LeaderboardAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LeaderboardAll(ctx, req.(*QueryAllLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticchain.tictactoe.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Game",
			Handler:    _Query_Game_Handler,
		},
		{
			MethodName: "GameAll",
			Handler:    _Query_GameAll_Handler,
		},
		{
			MethodName: "GameBoard",
			Handler:    _Query_GameBoard_Handler,
		},
		{
			MethodName: "GameBoardAll",
			Handler:    _Query_GameBoardAll_Handler,
		},
		{
			MethodName: "LeaderboardAll",
			Handler:    _Query_LeaderboardAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticchain/tictactoe/query.proto",
}
